# Generated by Django 5.0.14 on 2026-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('attiva', 'Attiva'), ('annullata', 'Annullata'), ('ritirata', 'Ritirata'), ('non_ritirata', 'Non ritirata'), ('scaduta', 'Scaduta')], default='attiva', max_length=20),
        ),
    ]
