# Generated by Django 5.2.15 on 2026-06-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0003_database_triggers'),
    ]

    operations = [
    migrations.RunSQL(
        sql=[
            "DROP TRIGGER IF EXISTS trg_lotto_bi_valida;",
            """
            CREATE TRIGGER trg_lotto_bi_valida
            BEFORE INSERT ON mensa_lottoinvenduto
            BEGIN
                SELECT RAISE(ABORT, 'Quantita iniziale non valida.')
                WHERE NEW.quantita_iniziale <= 0;

                SELECT RAISE(ABORT, 'Quantita disponibile non valida.')
                WHERE NEW.quantita_disponibile < 0
                   OR NEW.quantita_disponibile > NEW.quantita_iniziale;

                SELECT RAISE(ABORT, 'Data scadenza non valida.')
                WHERE NEW.data_scadenza < NEW.data_pubblicazione;

                SELECT RAISE(ABORT, 'Fascia oraria ritiro non valida.')
                WHERE NEW.ora_fine_ritiro <= NEW.ora_inizio_ritiro;

                SELECT RAISE(ABORT, 'Operatore non associato alla mensa del lotto.')
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM mensa_operatoremensa op
                    WHERE op.id = NEW.operatore_id
                      AND op.mensa_id = NEW.mensa_id
                );

                SELECT RAISE(ABORT, 'Non puoi inserire come disponibile un lotto gia scaduto.')
                WHERE NEW.stato = 'disponibile'
                  AND (
                      NEW.data_scadenza < DATE('now', 'localtime')
                      OR (
                          NEW.data_scadenza = DATE('now', 'localtime')
                          AND NEW.ora_fine_ritiro <= TIME('now', 'localtime')
                      )
                  );
            END;
            """,

            "DROP TRIGGER IF EXISTS trg_lotto_bu_valida;",
            """
            CREATE TRIGGER trg_lotto_bu_valida
            BEFORE UPDATE ON mensa_lottoinvenduto
            BEGIN
                SELECT RAISE(ABORT, 'Quantita iniziale non valida.')
                WHERE NEW.quantita_iniziale <= 0;

                SELECT RAISE(ABORT, 'Quantita disponibile non valida.')
                WHERE NEW.quantita_disponibile < 0
                   OR NEW.quantita_disponibile > NEW.quantita_iniziale;

                SELECT RAISE(ABORT, 'Data scadenza non valida.')
                WHERE NEW.data_scadenza < NEW.data_pubblicazione;

                SELECT RAISE(ABORT, 'Fascia oraria ritiro non valida.')
                WHERE NEW.ora_fine_ritiro <= NEW.ora_inizio_ritiro;

                SELECT RAISE(ABORT, 'Operatore non associato alla mensa del lotto.')
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM mensa_operatoremensa op
                    WHERE op.id = NEW.operatore_id
                      AND op.mensa_id = NEW.mensa_id
                );
            END;
            """,

            "DROP TRIGGER IF EXISTS trg_lotto_bu_blocca_disponibile_scaduto;",
            """
            CREATE TRIGGER trg_lotto_bu_blocca_disponibile_scaduto
            BEFORE UPDATE OF stato, data_scadenza, ora_fine_ritiro
            ON mensa_lottoinvenduto
            BEGIN
                SELECT RAISE(ABORT, 'Un lotto scaduto non puo tornare disponibile.')
                WHERE NEW.stato = 'disponibile'
                  AND (
                      NEW.data_scadenza < DATE('now', 'localtime')
                      OR (
                          NEW.data_scadenza = DATE('now', 'localtime')
                          AND NEW.ora_fine_ritiro <= TIME('now', 'localtime')
                      )
                  );
            END;
            """,

            "DROP TRIGGER IF EXISTS trg_lotto_au_esaurito;",
            """
            CREATE TRIGGER trg_lotto_au_esaurito
            AFTER UPDATE OF quantita_disponibile
            ON mensa_lottoinvenduto
            WHEN NEW.stato = 'disponibile'
                 AND NEW.quantita_disponibile = 0
            BEGIN
                UPDATE mensa_lottoinvenduto
                SET stato = 'esaurito'
                WHERE id = NEW.id;
            END;
            """,

            "DROP TRIGGER IF EXISTS trg_prenotazione_bi_valida;",
            """
            CREATE TRIGGER trg_prenotazione_bi_valida
            BEFORE INSERT ON mensa_prenotazione
            WHEN NEW.stato = 'attiva'
            BEGIN
                SELECT RAISE(ABORT, 'Quantita prenotata non valida.')
                WHERE NEW.quantita <= 0;

                SELECT RAISE(ABORT, 'Lotto non prenotabile.')
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM mensa_lottoinvenduto l
                    JOIN mensa_mensa m ON m.id = l.mensa_id
                    JOIN mensa_prodottoalimentare p ON p.id = l.prodotto_id
                    WHERE l.id = NEW.lotto_id
                      AND l.stato = 'disponibile'
                      AND l.quantita_disponibile >= NEW.quantita
                      AND l.data_scadenza >= DATE('now', 'localtime')
                      AND NOT (
                          l.data_scadenza = DATE('now', 'localtime')
                          AND l.ora_fine_ritiro <= TIME('now', 'localtime')
                      )
                      AND m.attiva = 1
                      AND p.attivo = 1
                );
            END;
            """,

            "DROP TRIGGER IF EXISTS trg_prenotazione_ai_decrementa_lotto;",
            """
            CREATE TRIGGER trg_prenotazione_ai_decrementa_lotto
            AFTER INSERT ON mensa_prenotazione
            WHEN NEW.stato = 'attiva'
            BEGIN
                UPDATE mensa_lottoinvenduto
                SET quantita_disponibile = quantita_disponibile - NEW.quantita
                WHERE id = NEW.lotto_id;
            END;
            """,

            "DROP TRIGGER IF EXISTS trg_prenotazione_bu_controlla_modifiche;",
            """
            CREATE TRIGGER trg_prenotazione_bu_controlla_modifiche
            BEFORE UPDATE OF stato, quantita, lotto_id
            ON mensa_prenotazione
            BEGIN
                SELECT RAISE(ABORT, 'Non puoi modificare lotto o quantita di una prenotazione.')
                WHERE NEW.quantita != OLD.quantita
                   OR NEW.lotto_id != OLD.lotto_id;

                SELECT RAISE(ABORT, 'Solo prenotazioni attive possono essere annullate.')
                WHERE NEW.stato = 'annullata'
                  AND OLD.stato != 'attiva';
            END;
            """,

            "DROP TRIGGER IF EXISTS trg_prenotazione_au_annullata_restituisce_lotto;",
            """
            CREATE TRIGGER trg_prenotazione_au_annullata_restituisce_lotto
            AFTER UPDATE OF stato
            ON mensa_prenotazione
            WHEN OLD.stato = 'attiva'
                 AND NEW.stato = 'annullata'
            BEGIN
                UPDATE mensa_lottoinvenduto
                SET quantita_disponibile =
                    CASE
                        WHEN quantita_disponibile + NEW.quantita > quantita_iniziale
                        THEN quantita_iniziale
                        ELSE quantita_disponibile + NEW.quantita
                    END
                WHERE id = NEW.lotto_id;

                UPDATE mensa_lottoinvenduto
                SET stato = 'disponibile'
                WHERE id = NEW.lotto_id
                  AND stato = 'esaurito'
                  AND quantita_disponibile > 0
                  AND NOT (
                      data_scadenza < DATE('now', 'localtime')
                      OR (
                          data_scadenza = DATE('now', 'localtime')
                          AND ora_fine_ritiro <= TIME('now', 'localtime')
                      )
                  );
            END;
            """,

            "DROP TRIGGER IF EXISTS trg_ritiro_bi_fascia_oraria;",
            """
            CREATE TRIGGER trg_ritiro_bi_fascia_oraria
            BEFORE INSERT ON mensa_ritiro
            BEGIN
                SELECT RAISE(ABORT, 'Il ritiro richiede una prenotazione attiva.')
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM mensa_prenotazione pr
                    WHERE pr.id = NEW.prenotazione_id
                      AND pr.stato = 'attiva'
                );

                SELECT RAISE(ABORT, 'Il ritiro e fuori dalla fascia oraria prevista.')
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM mensa_prenotazione pr
                    JOIN mensa_lottoinvenduto l ON l.id = pr.lotto_id
                    WHERE pr.id = NEW.prenotazione_id
                      AND l.data_scadenza = DATE('now', 'localtime')
                      AND l.ora_inizio_ritiro <= TIME('now', 'localtime')
                      AND l.ora_fine_ritiro > TIME('now', 'localtime')
                );
            END;
            """,

            "DROP TRIGGER IF EXISTS trg_ritiro_ai_aggiorna_prenotazione;",
            """
            CREATE TRIGGER trg_ritiro_ai_aggiorna_prenotazione
            AFTER INSERT ON mensa_ritiro
            BEGIN
                UPDATE mensa_prenotazione
                SET stato =
                    CASE NEW.esito
                        WHEN 'consegnato' THEN 'ritirata'
                        WHEN 'non_consegnato' THEN 'non_ritirata'
                        ELSE 'annullata'
                    END
                WHERE id = NEW.prenotazione_id;
            END;
            """,
        ],
        reverse_sql=[
            "DROP TRIGGER IF EXISTS trg_lotto_bi_valida;",
            "DROP TRIGGER IF EXISTS trg_lotto_bu_valida;",
            "DROP TRIGGER IF EXISTS trg_lotto_bu_blocca_disponibile_scaduto;",
            "DROP TRIGGER IF EXISTS trg_lotto_au_esaurito;",
            "DROP TRIGGER IF EXISTS trg_prenotazione_bi_valida;",
            "DROP TRIGGER IF EXISTS trg_prenotazione_ai_decrementa_lotto;",
            "DROP TRIGGER IF EXISTS trg_prenotazione_bu_controlla_modifiche;",
            "DROP TRIGGER IF EXISTS trg_prenotazione_au_annullata_restituisce_lotto;",
            "DROP TRIGGER IF EXISTS trg_ritiro_bi_fascia_oraria;",
            "DROP TRIGGER IF EXISTS trg_ritiro_ai_aggiorna_prenotazione;",
        ],
    ),
]

