# Generated by Django 5.2.15 on 2026-06-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0004_database_triggers_fix'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DROP TRIGGER IF EXISTS trg_lotto_bi_valida;",
                """
                CREATE TRIGGER trg_lotto_bi_valida
                BEFORE INSERT ON mensa_lottoinvenduto
                BEGIN
                    SELECT RAISE(ABORT, 'Quantita iniziale non valida.')
                    WHERE NEW.quantita_iniziale <= 0
                       OR NEW.quantita_iniziale > 100;

                    SELECT RAISE(ABORT, 'Quantita disponibile non valida.')
                    WHERE NEW.quantita_disponibile < 0
                       OR NEW.quantita_disponibile > 100
                       OR NEW.quantita_disponibile > NEW.quantita_iniziale;

                    SELECT RAISE(ABORT, 'Data scadenza non valida.')
                    WHERE NEW.data_scadenza < NEW.data_pubblicazione;

                    SELECT RAISE(ABORT, 'Fascia oraria ritiro non valida.')
                    WHERE NEW.ora_fine_ritiro <= NEW.ora_inizio_ritiro;

                    SELECT RAISE(ABORT, 'Operatore non associato alla mensa del lotto.')
                    WHERE NOT EXISTS (
                        SELECT 1
                        FROM mensa_operatoremensa op
                        WHERE op.id = NEW.operatore_id
                          AND op.mensa_id = NEW.mensa_id
                    );

                    SELECT RAISE(ABORT, 'Non puoi inserire come disponibile un lotto gia scaduto.')
                    WHERE NEW.stato = 'disponibile'
                      AND (
                          NEW.data_scadenza < DATE('now', 'localtime')
                          OR (
                              NEW.data_scadenza = DATE('now', 'localtime')
                              AND NEW.ora_fine_ritiro <= TIME('now', 'localtime')
                          )
                      );
                END;
                """,

                "DROP TRIGGER IF EXISTS trg_lotto_bu_valida;",
                """
                CREATE TRIGGER trg_lotto_bu_valida
                BEFORE UPDATE ON mensa_lottoinvenduto
                BEGIN
                    SELECT RAISE(ABORT, 'Quantita iniziale non valida.')
                    WHERE NEW.quantita_iniziale <= 0
                       OR NEW.quantita_iniziale > 100;

                    SELECT RAISE(ABORT, 'Quantita disponibile non valida.')
                    WHERE NEW.quantita_disponibile < 0
                       OR NEW.quantita_disponibile > 100
                       OR NEW.quantita_disponibile > NEW.quantita_iniziale;

                    SELECT RAISE(ABORT, 'Data scadenza non valida.')
                    WHERE NEW.data_scadenza < NEW.data_pubblicazione;

                    SELECT RAISE(ABORT, 'Fascia oraria ritiro non valida.')
                    WHERE NEW.ora_fine_ritiro <= NEW.ora_inizio_ritiro;

                    SELECT RAISE(ABORT, 'Operatore non associato alla mensa del lotto.')
                    WHERE NOT EXISTS (
                        SELECT 1
                        FROM mensa_operatoremensa op
                        WHERE op.id = NEW.operatore_id
                          AND op.mensa_id = NEW.mensa_id
                    );
                END;
                """,
            ],
            reverse_sql=[
                "DROP TRIGGER IF EXISTS trg_lotto_bi_valida;",
                "DROP TRIGGER IF EXISTS trg_lotto_bu_valida;",
            ],
        ),
    ]
